// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlitptrnqpsnqjciskxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1saXRwdHJucXBzbnFqY2lza3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDg5ODUsImV4cCI6MjA2NjE4NDk4NX0.TryNTaczYvMe26QZb5fzAb7IniK1cN00mCUKY4RrG04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);